container:
  image: cirrusci/bazel:0.9.0
  cpu: 8
  memory: 24G

test_task:
  install_script:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install -y gcc-4.8 g++-4.8 python2.7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
    - sudo pip install wheel
  ci_script:
    - which gcc-4.8
    - gcc --version
    - which g++-4.8
    - g++ --version
    - which python
    - python -V
    - which python2.7
    - python2.7 -V
    - scripts/cirrus/ci.sh