group: edge

sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  # download and install bazel
  - wget -q 'https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel-0.9.0-installer-linux-x86_64.sh'
  - chmod +x bazel-0.9.0-installer-linux-x86_64.sh
  - ./bazel-0.9.0-installer-linux-x86_64.sh --user

before_script:
  # install python module for wheel files
  # required for python packaging
  - sudo pip install wheel

script:
  - scripts/travis/ci.sh
